import Head from 'next/head'
import Header from './Header'
import Sidebar from './Sidebar'

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Food app</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Sidebar />
            <main className='ml-auto lg:w-[85%]'>
                <Header />
                <section className='h-screen px-10 py-5'>
                    {children}
                </section>
            </main>
        </>
    )
}

export default Layout